### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by FedericoBiccheddu** [sikanhe/gqtx#14]
After reading #12, I can try to add some integration tests with `graphql-js` in order to test the correctness of the schema generated.

This can lead to:
\- add a CI
\- increment the package quality
\- self-documenting some package aspects
\- clean up dependencies currently needed only for examples

**Comment by n1ru4l** [comment]
I think it also makes sense to test the TypeScript API of this library

**Comment by FedericoBiccheddu** [comment]
I agree! I've never tested TS types, but can try. 

[dtslint](https://github.com/microsoft/dtslint) seems to be a valid option. 

Can you help me? :smile:

**Comment by n1ru4l** [comment]
> If you are writing the library in TypeScript, don't use dtslint (https://github.com/microsoft/dtslint#setup)

I think it makes more sense to use the options built into the typescript compiler: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#-ts-expect-error-comments

Also having TypesCript 3.9.3 as a development dependency in this project does not require consumers using TypeScript version 3.9.3 (regarding your comment https://github.com/sikanhe/gqtx/pull/12#issuecomment-636392012)

**Comment by FedericoBiccheddu** [comment]
I'm working again on this issue.

I'd like focus exclusively  in testing output types because of my lack of experience in testing types.
