### ISSUE TITLE
`relay.js` missing from last beta release

### ISSUE THREAD

**Issue by zth** [sikanhe/gqtx#30]
Hi! Eager to try the new beta with Relay helpers! 😄  However, it seems like the actual `relay.js` file isn't in the shipped package, but only the type definition is.

![image](https://user-images.githubusercontent.com/1457626/103304489-0ee54680-4a09-11eb-87d8-e748c4037308.png)

**Comment by sikanhe** [comment]
ahh will fix 😅

**Comment by dan003400** [comment]
Assuming this is causing these errors?

```
const relay = gqtx_1.createRelayHelpers(t);
                     ^
TypeError: gqtx_1.createRelayHelpers is not a function
```

**Comment by n1ru4l** [comment]
should be fixed on master

**Comment by MikeAliG** [comment]
Hello, I'm running on v0.8.0-beta.0 and `relay.js` file doesn't exist in the module folder. Is this expected? Because it's breaking the build.

**Comment by n1ru4l** [comment]
Th beta does not include these changes, try the canary tag on npm

**Comment by MikeAliG** [comment]
Awesome! Fixed. Thanks.
