### ISSUE TITLE
Please provide an ESM build

### ISSUE THREAD

**Issue by schickling** [sikanhe/gqtx#33]
Thanks for this nice and simple library. It would be great if you'd provide an ESM build of this library as well. (In case you're not familiar with how to do this, you can reference [how Nexus is built](https://github.com/graphql-nexus/nexus/blob/main/package.json#L33).)

**Comment by sikanhe** [comment]
@schickling Good idea, will have that soon

**Comment by sikanhe** [comment]
Implemented in https://github.com/sikanhe/gqtx/pull/42
