### ISSUE TITLE
README example is broken

### ISSUE THREAD

**Issue by Ericnr** [sikanhe/gqtx#38]
Fields defined with `t.ID` should be able to take either a string or a number, as the default behavior is to stringify the value, but currently it expects it to be a string. The readme example runs into this problem
```ts
type User = {
  id: number;
  role: Role;
  name: string;
};

const UserType = t.objectType<User>({
  name: 'User',
  description: 'A User',
  fields: () => [
    t.defaultField('id', t.NonNull(t.ID)) // Type 'string | null' is not assignable to type 'number'.
...
```

**Comment by sikanhe** [comment]
Good catch, this became outdated due to https://github.com/sikanhe/gqtx/pull/13.

**Comment by sikanhe** [comment]
Fixed in master
