### ISSUE TITLE
defaultField does not raise a TypeError if the Resolver  input type does not match the object source/output type

### ISSUE THREAD

**Issue by n1ru4l** [sikanhe/gqtx#4]
Causes no TypeScript error:

```ts
export type IMessageType = {
  id: string;
  authorName: string;
  rawContent: string;
  createdAt: Date;
};

export const GraphQLMessageType = t.objectType<IMessageType>({
  name: "Message",
  fields: () => [
    t.defaultField("id", t.NonNull(t.ID)),
    t.defaultField("authorName", t.NonNull(t.String)),
    t.defaultField("rawContent", t.NonNull(t.String)),
    t.field("createdAt", {
      type: t.NonNull(t.String),
      resolve: message => String(message.createdAt)
    })
  ]
});

export type LiveSubscriptionType = {
  query: {};
};

const GraphQLLiveSubscriptionType = t.objectType<
  LiveSubscriptionType,
  IContextType
>({
  name: "LiveSubscription",
  fields: () => [
    t.field("query", {
      type: GraphQLMessageType,
      resolve: i => i.query
    })
  ]
});
```

Causes TypeScript error:

```diff
export type IMessageType = {
  id: string;
  authorName: string;
  rawContent: string;
  createdAt: Date;
};

export const GraphQLMessageType = t.objectType<IMessageType>({
  name: "Message",
  fields: () => [
    t.defaultField("id", t.NonNull(t.ID)),
    t.defaultField("authorName", t.NonNull(t.String)),
    t.defaultField("rawContent", t.NonNull(t.String)),
    t.field("createdAt", {
      type: t.NonNull(t.String),
      resolve: message => String(message.createdAt)
    })
  ]
});

export type LiveSubscriptionType = {
-   query: {};
+  query: { lel: string };
};

const GraphQLLiveSubscriptionType = t.objectType<
  LiveSubscriptionType,
  IContextType
>({
  name: "LiveSubscription",
  fields: () => [
    t.field("query", {
      type: GraphQLMessageType,
      resolve: i => i.query
    })
  ]
});

```

Error Message:

```
ype '{ lel: string; }' is not assignable to type 'IMessageType | Promise<IMessageType>'.
  Type '{ lel: string; }' is missing the following properties from type 'Promise<IMessageType>': then, catch, [Symbol.toStringTag], finally
```

Expected behavior:

Empty object definition: `{}` should also cause a TypeScript Error.

__________

```ts
export type IMessageType = {
  id: string;
  authorName: string;
  rawContent: string;
  createdAt: Date;
};

export type IRootValueType = {
  messages: IMessageType[];
};

export type IGetRootValueType = () => RootValueType;

export type IContextType = {
  eventEmitter: EventEmitter;
  mutateState: (producer: (root: IRootValueType) => void) => void;
  addMessage: (message: IMessageType) => void;
};


const Query = t.queryType<IContextType, IRootValueType>({
  fields: [...MessageModule.queryFields]
});

export type LiveSubscriptionType = {
  query: { swag: string };
};

const GraphQLLiveSubscriptionType = t.objectType<
  LiveSubscriptionType,
  IContextType
>({
  name: "LiveSubscription",
  // does not raise an error but should because LiveSubscriptionType["query"] is not of type `IRootValueType`
  fields: () => [t.defaultField("query", Query)]
});
```

The following correctly raises a type error:

```ts
export type LiveSubscriptionType = {
  query: { swag: string };
};

const GraphQLLiveSubscriptionType = t.objectType<
  LiveSubscriptionType,
  IContextType
>({
  name: "LiveSubscription",
  fields: () => [
    t.field("query", {
      type: Query,
      resolve: i => i.query
    })
  ]
});
```

```
Type '{ swag: string; }' is not assignable to type 'IRootValueType | Promise<IRootValueType>'.
  Type '{ swag: string; }' is missing the following properties from type 'Promise<IRootValueType>': then, catch, [Symbol.toStringTag], finally
```

**Comment by sikanhe** [comment]
Query, Mutation, and Subscription root objects do not have a `source`

**Comment by sikanhe** [comment]
Why are we passing the RootQuery type to another field?

**Comment by sikanhe** [comment]
The `t.queryType

**Comment by sikanhe** [comment]
Btw I am happy to be corrected if you can show me in the Spec or another graphql implementation that contradicts this

**Comment by n1ru4l** [comment]
> source to void becuase the root types should not have source

@sikanhe https://github.com/graphql/graphql-js/blob/278bde0a5cd71008452b555065f19dcd1160270a/src/graphql.d.ts#L57

https://stackoverflow.com/a/54309820

> Why are we passing the RootQuery type to another field?

It is a common practice to return the Query type from Mutation fields so you can query for the updated data.

In my specific use-case I am using https://github.com/D1plo1d/graphql-live-subscriptions

Which exposes the Query Type as a Field on the Subscriptions type. AFAIK there is nothing in the spec that prohibits returning the Query type (which is still a basic Type) from a bin Root Field.

**Comment by sikanhe** [comment]
mmm, yea the defaultField is made for people who are too lazy to type out a full resolver (which i never get because programming productivity is never limited by keystroke speed XD). But I think what is happening is due to typescript inference failing to refer the correct thing here. If you have any idea let me know. But i might have a better API that is better for inference

**Comment by n1ru4l** [comment]
Yeah, I think the type `{}` has some kind of special meaning, I will try to do some research and let you know!

**Comment by sikanhe** [comment]
An interesting observation is that if we wrap the return type with `t.NonNull` it errors correctly

**Comment by n1ru4l** [comment]
I am also curious why you decided using an array for the field definitions instead of an object where the key represents the field names? What would happen in case two fields have the same name?

**Comment by sikanhe** [comment]
@n1ru4l thank you so much, i did a this a couple months ago, and I am waiting for people to wanting to use it first before diving more into it and make it more robust and add docs. So thank you to taking the chance to give it a try!

The reason for array of functions is to make type inference work on a per field basis - ever wonder why graphql-js cannot type their definition properly? (everything is typed `any`) because object shape makes this much harder. 

imagining following type: 
```ts 
type fields = {
  [key: string]: {
    type: T,
    resolve: () => T
  }
}
```
What is `T` here ? T is the output type of a single field, but they have to be different per field! there is no way to such statement in Ts: 

> T is different on every Field[Key], but must be consistant within each field

So to solve that, we need to wrap each field in a function to make sure, even thought return type of each field can be "Any" when talking about an entire object, we still want to ensure that each field is constructed properly - the type of field needs to align with the output of resolver:

```ts 
// In a field, the type of the field must match the return of resolve! (ignore Src and Ctx for now)
type fieldDefFn<TOutput> = ({ 
   type: GraphQLType<TOutput>, 
   resolve: (src) => TOutput
}) => ...
```

Now even though fieldDef can return anything really, the argument you pass to a fieldDef must comply with the rule that `type` needs to agree with `resolve`. and this is enough for our needs!
```ts
fields: {
   foo: fieldDef<{foo: number}>(
     type: GraphQLString
     resolve: (src) => src.foo // type error because baz is not a string
   })
}
```

But what about default fields? with default fields, we need to make sure the field name is a key of the object of `Src`. But the field name lives outside of our `fieldDef` function! , so somehow we need to include the field name in the fieldDefFn type so that we can ensure the name is type checked: 
```ts
type fieldDefFn<Src, FieldName extends keyof Src> = ({ 
  name: FieldName
  type: Scalar<TTOutput>, 
  resolve: (src) => Output 
})  => ...
```
This works, but this is not a valid JS, since now we don't have a key for object anymore
```ts
fields: {
   fieldDef(
     "foo",
     type: GraphQLString
     resolve: (src) => src.foo
   })
},
```
So we need an array 
```
fields: [
   fieldDef(
     "foo",
     type: GraphQLString
     resolve: (src) => src.foo
   })
]
```

**Comment by n1ru4l** [comment]
I noticed the following does also not raise a TypeScript error. It seems like there will be no error in case the structure of the type overlaps partially, which makes also sense why it does not complain about `{}`.

```tsx
import t from "gqtx";
import { IContextType } from "../../@types";

export type IMessageType = {
  id: string;
  authorName: string;
  rawContent: string;
  createdAt: Date;
};

export const GraphQLMessageType = t.objectType<IMessageType>({
  name: "Message",
  fields: () => [
    t.defaultField("id", t.NonNull(t.ID)),
    t.defaultField("authorName", t.NonNull(t.String)),
    t.defaultField("rawContent", t.NonNull(t.String)),
    t.field("createdAt", {
      type: t.NonNull(t.String),
      resolve: message => String(message.createdAt)
    })
  ]
});

export type LiveSubscriptionType = {
  query: { id: string };
};

const GraphQLLiveSubscriptionType = t.objectType<
  LiveSubscriptionType,
  IContextType
>({
  name: "LiveSubscription",
  fields: () => [
    t.field("query", {
      type: GraphQLMessageType,
      resolve: i => i.query
    })
  ]
});
```

**Comment by n1ru4l** [comment]
Changing the type definition like the following seems to solve this issue:

```tsx
type PromiseOrPlain<A> = A | Promise<A>
export declare function field<Ctx, Src, Arg, Out, TOutputType extends OutputType<any, any> = any>(name: string, { type, args, resolve, description, deprecationReason, }: {
    type: TOutputType;
    args?: ArgMap<Arg>;
    description?: string;
    deprecationReason?: string;
    resolve: (src: Src, args: TOfArgMap<ArgMap<Arg>>, ctx: Ctx, info: graphql.GraphQLResolveInfo) => PromiseOrPlain<TOutputType extends OutputType<any, infer E> ? E : never>
}): Field<Ctx, Src, Out, Arg>;
```

Very good article regarding this: https://artsy.github.io/blog/2018/11/21/conditional-types-in-typescript.

It now produces the following error:

```
Type '{ id: string; }' is not assignable to type 'PromiseOrPlain<IMessageType>'.
  Type '{ id: string; }' is missing the following properties from type 'IMessageType': authorName, rawContent, createdAtts(2322)
```

**Comment by n1ru4l** [comment]
Something like this is possible to handle each possible case:

```
export declare function field<Ctx, Src, Arg, Out, TOutputType extends OutputType<any, any> = any>(name: string, { type, args, resolve, description, deprecationReason, }: {
    type: TOutputType;
    args?: ArgMap<Arg>;
    description?: string;
    deprecationReason?: string;
    resolve: (src: Src, args: TOfArgMap<ArgMap<Arg>>, ctx: Ctx, info: graphql.GraphQLResolveInfo) => PromiseOrPlain<
      TOutputType extends ListType<any, OutputType<any, infer A>>
      ? A
      : TOutputType extends NonNull<any, OutputType<any, infer B>>
        ? B
        : TOutputType extends OutputType<any, infer C>
          ? C | null
          : never
    >
```
const GraphQLLiveSubscriptionType = t.objectType<
  LiveSubscriptionType,
  IContextType
>({
  name: "LiveSubscription",
  fields: () => [
    t.field("query", {
      type: GraphQLMessageType,
      resolve: i => i.query
    }),
    t.field("query", {
      type: GraphQLMessageType,
      resolve: i => null
    }),
    t.field("aaa", {
      type: t.NonNull(GraphQLMessageType),
      resolve: i => null
    }),
    t.field("aaa", {
      type: t.NonNull(GraphQLMessageType),
      resolve: i => i.query
    }),
    t.field("aaa", {
      type: t.List(GraphQLMessageType),
      resolve: i => [i.query, null]
    }),
    t.field("aaa", {
      type: t.List(t.NonNull(GraphQLMessageType)),
      resolve: i => [i.query]
    })
  ]
});
```

It might make sense to have some kind of schema definition in the repository that ensures the types are inferred correctly.

**Comment by n1ru4l** [comment]
I just cloned master and it seems like the issue does not exist there anymore.

**Comment by sikanhe** [comment]
In master i have a new feature added: https://github.com/sikanhe/gqtx/pull/7

**Comment by n1ru4l** [comment]
@sikanhe Yeah I am actually a bit confused, I manually edited the type-definition in the project I was using, maybe I fucked something up. Anyways, would you accept a pull request that adds some code samples that we can test with https://github.com/microsoft/dtslint#write-tests and a Github Action that runs those, to ensure there is no regression regarding this?

**Comment by sikanhe** [comment]
@n1ru4l Would love for some help on that, that'd be amazing!
