### ISSUE TITLE
canary release does not include transpiled js code

### ISSUE THREAD

**Issue by n1ru4l** [sikanhe/gqtx#41]
See https://unpkg.com/browse/gqtx@0.8.1-800c992a.0/dist/

@sikanhe It seems like https://github.com/sikanhe/gqtx/blob/800c992a8217d508fbc0ed495f3ebe90ecdcf6ae/package.json#L31 this is executed after/while publishing?

**Comment by sikanhe** [comment]
Interesting, not possible to include a step to call `tsc` before we publish in the github action?

**Comment by sikanhe** [comment]
Can we close this one? @n1ru4l

**Comment by n1ru4l** [comment]
yes
