### ISSUE TITLE
Mutation `fields` signature

### ISSUE THREAD

**Issue by FedericoBiccheddu** [sikanhe/gqtx#43]
I noticed mutations `fields` requires a callback, but subscription and query fields not.

https://github.com/sikanhe/gqtx/blob/7cf0d3afa9579e63ed0f32cdc2d09e8790ffd896/src/define.ts#L483

Removing the callback from the public api the callback could be an implementation detail here:
https://github.com/sikanhe/gqtx/blob/7cf0d3afa9579e63ed0f32cdc2d09e8790ffd896/src/define.ts#L489

There are reasons that I am missing? In case this is not intended, I can submit a PR.

**Comment by sikanhe** [comment]
Yea it shouldn't be inconsistent - happy to accept PR here
