### ISSUE TITLE
Add implicit field resolution without the need of `defaultField`

### ISSUE THREAD

**Issue by FedericoBiccheddu** [sikanhe/gqtx#48]
I was thinking about an implicit resolution of `field` in order to have the same behavior as GraphQL.

At the moment there are two ways of resolving fields with the same result in return:
Explicit:
```ts
const droidType = t.objectType<Droid>({
  // ...
  fields: () => [
    t.field('id', {
      // Please note type is under a "configuration" object
      type: t.NonNull(t.ID), 
      resolve: (src) => src.id
    }),
    // ...
  ],
});
```

Implicit:
```ts
const droidType = t.objectType<Droid>({
  // ...
  fields: () => [
    // Please note the type is mandatory
    t.defaultField('id', t.NonNull(t.ID), {
      resolve: (src) => src.id
    }),
    // ...
  ],
});
```

To simplify the API having one way to obtain the same result in different ways, I did experiment with this approach:
- the object type is now always provided as second argument
- `field` becomes the only way to resolve an object; if no resolve is provided, it will resolve using the `defaultField` approach

The code will be something like:
```ts
const droidType = t.objectType<Droid>({
  // ...
  fields: () => [
    // Explicit resolver if needed
    t.field('id', t.NonNull(t.ID), {
      resolve: (src) => src.id
    }),

    // Implicit resolver if we want to resolve source's 'name' property
    t.field('name', t.NonNull(t.String)),
    // ...
  ],
});
```

What do you folks think?

**Comment by n1ru4l** [comment]
I like the idea.

Would the following be a compiler error?

```tsx
type Droid {
  id: string;
  name: number; // this is number instead of array
}
const droidType = t.objectType<Droid>({
  // ...
  fields: () => [
    t.field('id', t.NonNull(t.ID), {
      resolve: (src) => src.id
    }),
    // will this be a compiler error because Droid["name"] is number instead of string?
    t.field('name', t.NonNull(t.String)),
  ],
});
```

**Comment by FedericoBiccheddu** [comment]
It should, but at the moment there is no inference from `Src` so it will pass.

I will try and update #49 to fix this scenario.
