### ISSUE TITLE
subscriptionField.subscribe should allow access to the source/root property

### ISSUE THREAD

**Issue by n1ru4l** [sikanhe/gqtx#5]
Currently, only args, context and info are passed into the subscribe function. The root/srcc should be accessible as well.

**Comment by sikanhe** [comment]
are you talking about `subscriptionField` resolver? The subscription resolvers do not take a source argument becuase they are toplevel under `subscription` object

**Comment by n1ru4l** [comment]
@sikanhe The root property is omitted here: https://github.com/sikanhe/gqtx/blob/431d6f16aaef338746cf6d6df3a39a02b56e2191/src/build.ts#L56

**Comment by sikanhe** [comment]
https://github.com/sikanhe/gqtx/pull/6
