### ISSUE TITLE
Resolve function is necessary when a built-in scalar can be undefined

### ISSUE THREAD

**Issue by Emilios1995** [sikanhe/gqtx#63]
In the following code,
```
type SearchCriteria = {
  minPrice?: number,
  maxPrice?: number,
}

const SearchCriteria = t.objectType<SearchCriteria>({
  name: "SearchCriteria",
  fields: () => [
    t.field({ name: 'minPrice', type: t.Int , resolve: ({minPrice}) => minPrice }),
    t.field({ name: 'maxPrice', type: t.Int , resolve: ({maxPrice}) => maxPrice }),
  ]
})

```

The compiler throws an error if I don't provide the `resolve` function. The reason is that `t.Int` is of type `Scalar<number | null>`, while my `SearchCriteria.minPrice` is of type `number | undefined`, so the later doesn't extend the former.

It would be great if the built in scalars (if they're not non-nullable) supported the `undefined` value too, like so `Int: Scalar<number | null | undefined>`.

**Comment by sikanhe** [comment]
GraphQL does not understand `undefined`. You want `resolve: ({minPrice}) => minPrice ?? null`

**Comment by Emilios1995** [comment]
> GraphQL does not understand `undefined`. You want `resolve: ({minPrice}) => minPrice ?? null`
> 
> 
> 
> I get that its a little inconvenient though.  I actually suggest you changing the type definition of `SearchCriteria` to use `number | null` 


Thanks for answering. I understand that absent fields have to be represented as `null` rather than `undefined` because otherwise they would be missing from the serialized JSON, but I was under the impression that `graphql-js` will just convert `undefined` values to `null`—isn't that the case?

**Comment by n1ru4l** [comment]
@Emilios1995 Actually you are right: https://stackblitz.com/edit/graphql-pkmsvz?file=index.js

**Comment by sikanhe** [comment]
Mhmm good catch - maybe we should do this

**Comment by sikanhe** [comment]
PR to fix this in https://github.com/sikanhe/gqtx/pull/65

**Comment by sikanhe** [comment]
In master

**Comment by Emilios1995** [comment]
Thanks a lot!
