### ISSUE TITLE
TypeScript type definitions don't work in ESM projects

### ISSUE THREAD

**Issue by andrew0** [sikanhe/gqtx#72]
When I try to import gqtx in a TypeScript project with the `moduleResolution` option set to `nodenext`, TypeScript can't find the correct type definitions: https://stackblitz.com/edit/typescript-dfnpmb?file=index.ts

<img width="442" alt="image" src="https://github.com/sikanhe/gqtx/assets/739172/f069817f-43b5-452a-b176-e4cf01d227cd">

I think this is because the package.json file for this library has `"type": "module"`, but the TypeScript definition files use extensionless imports.

**Comment by sikanhe** [comment]
Will be fixed in 0.9.1: https://github.com/sikanhe/gqtx/pull/73

https://stackblitz.com/edit/typescript-bxurk2?file=package.json,index.ts
